site_name: IBM Cloud Adoption
repo_url: https://github.com/dwakeman/cloud-adoption-ibn
edit_uri: ''
nav:
  - Home: index.md
  - Resilient Applications:
    - HA app considerations: ha-app/ha-app.md
    - Creating the Environment: ha-app/create-env.md
    - HA app deployment: ha-app/deploy-ha-app.md
  - Disaster Recovery: 
    - Overview: disaster-recovery/disaster-recovery.md
  - Custom Domains:
        Create a domain: custom-domain/create-domain.md
        Manage your domain: custom-domain/manage-domain.md
        Configure domain for OpenShift: custom-domain/domain-with-openshift.md
  - Infrastructure:
    - Infrastructure as Code (IaC): infrastructure/iac.md
    - Schematics: infrastructure/schematics.md
    - Virtual Private Cloud: infrastructure/vpc.md
    - Software Defined Storage: infrastructure/sds.md
  - IBM Cloud Platform:
    - OpenShift on IBM Cloud: cloud-platform/openshift-ibm-cloud.md
    - IBM Cloud Operator: cloud-platform/ibm-cloud-operator.md
    - Key Protect: cloud-platform/key-protect.md
  - IBM Cloud Satellite:
    - Overview: satellite/index.md
    - Create a Satellite Location:
      - IBM Cloud:
        - Classic Infrastructure: 
          - Prerequisites: satellite/ibm-cloud/classic/prerequisites.md
          - Create Hosts: satellite/ibm-cloud/classic/create-hosts.md
          - Create Location: satellite/ibm-cloud/classic/create-location.md
          - Attach Hosts: satellite/ibm-cloud/classic/attach-hosts.md
          - Assign Hosts to Location: satellite/ibm-cloud/classic/assign-hosts.md
        - VPC:
          - Prerequisites: satellite/ibm-cloud/vpc/prerequisites.md
          - Create Location: satellite/ibm-cloud/vpc/create-location.md
        - IBM Cloud for Government:
          - Prerequisites: satellite/ibm-cloud/ic4g/prerequisites.md
      - AWS:
        - Create Location: satellite/aws/create-location.md
        - Prerequisites: satellite/aws/prerequisites.md
        - Create Hosts: satellite/aws/create-hosts.md
        - Assign Hosts to Location: satellite/aws/assign-hosts.md
    - Create an OpenShift Cluster: satellite/openshift/create-cluster.md
  - Hybrid Cloud:
    - Deploying a Hybrid Cloud Application: hybrid-cloud/hybrid.md
  - Developer Experience: 
    - Overview: dev-tools/dev-experience.md
    - CodeReady Workspaces: dev-tools/crw.md
theme: material
markdown_extensions:
  - admonition
